language: node_js
node_js:
  - "node"
script:
  - echo 'Deploying to Firebase'
install:
  - npm install -g firebase-tools
cache:
  directories:
    - node_modules
after_success:
  - firebase deploy --project "$FIREBASE_PROJECT" --token "$FIREBASE_TOKEN"
